### ISSUE TITLE
Bug when using regex

### ISSUE THREAD

**Issue by NelsonGNP** [rapidpro/surveyor#25]
Hi guys,

I´m trying to use a regex to filter some answers, however, on android version 7+ the app is not handling the query (see attached). ps.: it works on older versions like 6.1, so I think that the Android SDK that handles regex, has changed after this version. 

![screenshot_20180611-120433](https://user-images.githubusercontent.com/39569804/41241548-99a33b58-6d73-11e8-9821-4fee85e736dd.png)

[surveyor-debug.txt](https://github.com/rapidpro/surveyor/files/2090658/surveyor-debug.txt)

**Comment by rowanseymour** [comment]
Interesting. This is coming from `Pattern.compile(...)` which supports the flag `Pattern. UNICODE_CHARACTER_CLASS` in Java 1.7 but not in earlier versions. We handle this by using reflection in https://github.com/rapidpro/expressions/blob/master/java/src/main/java/io/rapidpro/expressions/utils/ExpressionUtils.java#L224 to determine if that constant is defined... maybe there is a version of the Android SDK where it's defined but not supported?

**Comment by NelsonGNP** [comment]
I tested on an Android 7.1.2, and a colleague tested on 8.1.0, both versions didn´t work, and when a colleague tested with an Andoird 6, worked.

**Comment by rowanseymour** [comment]
Yeah you're right - looks like that constant is defined but not supported on Android 7+.. will make make changes to remove it
