### ISSUE TITLE
Large apk size

### ISSUE THREAD

**Issue by allancslima** [rapidpro/surveyor#52]
Is there any possibility to build a smaller apk (disregarding the ProGuard)? That's, swapping the "goflow" module (more than 30 MB) by a equivalent smaller.

Like Nyaruka version 13.1.0 with 7,7 MB of size:
https://play.google.com/store/apps/details?id=io.rapidpro.surveyor

**Comment by rowanseymour** [comment]
Surveyor is in the store as an Android App Bundle so the download size will vary between devices. On my Pixel 3 with Android 9 it's about 7.8MB. Curious if you've seen downloads much bigger than that. Are you building your own fork of the APK?

**Comment by allancslima** [comment]
I built an apk in master branch of this repository even. I saw the goflow module and there various architectures in JNI folder, so the difference between file sizes is this, the Play Store delivers an "different" app for each device, alright?

**Comment by rowanseymour** [comment]
Yeah. The goflow AAR file is pretty huge but you shouldn't end up with a final download as big as that.
