### ISSUE TITLE
Enter and point to any IP address

### ISSUE THREAD

**Issue by AlexandrosPas** [rapidpro/surveyor#58]
In RapidPro SMS Channel Android app after tapping 11 times on Rapidpro logo we could enter any IP address (own server deployment). RapidPro Surveyor doesn't include this option, when will this be available ?

**Comment by rowanseymour** [comment]
I'm not sure the purpose of this repo is to be a generic Surveyor release for different deployments.. so...

- Currently if you check out the code and make a debug build you'lll see the option to change URL - this is what we use during development
- You can fork this repo and customize the URL which is just a resource string and other parts of the branding - this is what we do to make a release for http://textit.in
- You can submit a PR to add a function like what we have in the SMS channel app

**Comment by AlexandrosPas** [comment]
The only available RapidPro android application in Google Play is now RapidPro Surveyor, SMS Channel app in no more available in Google Play. Therefore I'd suggest we open a PR to include this functionality in Surveyor in order for all of us with non-UNICEF credentials to be able to continue our projects and support our partnerships.

**Comment by rowanseymour** [comment]
You're welcome to open a PR for that but I honestly think you'd provide a better experience for your users if you fork this repo and customize the URL and branding. That's what we do for Textit which is non-UNICEF. Tapping a logo 11 times works for developers but isn't an optimal user experience.
